# Generated by Django 2.2.14 on 2020-08-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=70)),
                ('dname', models.CharField(max_length=70)),
                ('pname', models.CharField(max_length=70)),
                ('bookingdate', models.DateField()),
                ('appointmentdate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='doctorsmodel',
            name='pno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorsmodel',
            name='specialisation',
            field=models.CharField(choices=[('Dentist', 'Dentist'), ('Teeth Nose and Throat', 'Teeth Nose and Throat'), ('Cardiac', 'Cardiac'), ('Kidney', 'Kidney')], max_length=70),
        ),
    ]
