# Generated by Django 2.2.14 on 2020-08-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200826_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='dname',
            field=models.CharField(choices=[('vinay singh', 'vinay singh'), ('akash', 'akash'), ('rakesh singh', 'rakesh singh')], max_length=70),
        ),
    ]
