# Generated by Django 2.2.14 on 2020-08-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200827_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='dname',
            field=models.CharField(max_length=70),
        ),
    ]
