# Generated by Django 2.2.14 on 2020-08-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200827_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='dname',
            new_name='docname',
        ),
    ]
